using System.Collections.Generic;

namespace MarksEntry.MarksEntryClasses;

internal class GenericSkillsAutomator
{
	public static List<FeedbackEntry> GenericSkillsSource => new List<FeedbackEntry>
	{
		new FeedbackEntry("Positive Comments", "Confident, positive and a great role model for the classmates."),
		new FeedbackEntry("Positive Comments", "Frequently among the first to help and mentor other classmates. Is a valuable part of the classroom."),
		new FeedbackEntry("Positive Comments", "You have shown excellent ability to set goals and be persistent in achieving them."),
		new FeedbackEntry("Positive Comments", "You are interested in own learning, you listen attentively, and make a solid effort to avoid distractions that could interrupt the learning process."),
		new FeedbackEntry("Positive Comments", "Accountable and responsible. Makes smart decisions, admits mistakes and listens to opportunities to improve."),
		new FeedbackEntry("Positive Comments", "Relates well to classmates and appreciates different perspectives and experiences."),
		new FeedbackEntry("Positive Comments", "Manages emotions maturely and responds to feedback appropriately."),
		new FeedbackEntry("Positive Comments", "Always looks for ways to be helpful in the classroom."),
		new FeedbackEntry("Positive Comments", "Dependable and reliable, follows directions effectively, and follows through on commitments and others."),
		new FeedbackEntry("Positive Comments", "Thoughtful, insightful and thorough in written and verbal communication, and has a talent for expressing $ ideas clearly."),
		new FeedbackEntry("Positive Comments", "You work well with classmates in group work and often takes a leadership role."),
		new FeedbackEntry("Positive Comments", "# shows a positive attitude with classmates in group projects and activities, and both takes and gives suggestions and directions effectively."),
		new FeedbackEntry("Positive Comments", "# shows maturity when solving problems with classmates and uses good communication."),
		new FeedbackEntry("Positive Comments", "# excels at applying what $ learns in the classroom to real-world and real-life situations."),
		new FeedbackEntry("Positive Comments", "# is an enthusiastic member of the class and shows willingness to learn."),
		new FeedbackEntry("Positive Comments", "# shows responsible behavior, works well with a group and shows appreciation for the efforts of classmates."),
		new FeedbackEntry("Positive Comments", "Focused during class and contributes ideas willingly."),
		new FeedbackEntry("Positive Comments", "Performs independent work with confidence and focus."),
		new FeedbackEntry("Positive Comments", "Works independently and takes pride in work done well."),
		new FeedbackEntry("Positive Comments", "Focused in class and willingly participates in group discussion."),
		new FeedbackEntry("Positive Comments", "# is very conscientious and shows excellent effort and care with daily work."),
		new FeedbackEntry("Positive Comments", "Demonstrates a willing and conscientious effort in daily work."),
		new FeedbackEntry("Positive Comments", "# shows a conscientious effort to learn."),
		new FeedbackEntry("Positive Comments", "# has done a great job facing and overcoming big challenges this year. Please continue to nurture and encourage this behavior over the summer."),
		new FeedbackEntry("Positive Comments", "You show responsibility and follows directions whenever they are given."),
		new FeedbackEntry("Positive Comments", "# listens to and follows directions precisely and attentively."),
		new FeedbackEntry("Positive Comments", "You follow directions promptly and accurately."),
		new FeedbackEntry("Needs Improvement", "You are encouraged to demonstrate more responsible attitudes and behavior in the classroom."),
		new FeedbackEntry("Needs Improvement", "You need to show more appropriate behavior when interacting with classmates."),
		new FeedbackEntry("Needs Improvement", "Pay attention to the use of appropriate language at all times."),
		new FeedbackEntry("Needs Improvement", "# requires encouragement to listen attentively during group sharing times."),
		new FeedbackEntry("Needs Improvement", "# needs to listen to directions more attentively during lessons."),
		new FeedbackEntry("Needs Improvement", "# would benefit from showing a greater desire to contribute ideas in class."),
		new FeedbackEntry("Needs Improvement", "# needs frequent reminders to be attentive during instructions and lessons."),
		new FeedbackEntry("Needs Improvement", "# needs to improve $ cooperation in group settings. Should work on voicing feelings and opinions and listening to others."),
		new FeedbackEntry("Needs Improvement", "# needs to improve $ work with others. $ must ensure to accept a share of the work when participating in a group assignment."),
		new FeedbackEntry("Needs Improvement", "# needs to improve on working independently and be sure to ask for assistance only when it is needed."),
		new FeedbackEntry("Needs Improvement", "# often struggles to focus in class, which harms $ ability to engage well with class activities and assignments."),
		new FeedbackEntry("Needs Improvement", "# is encouraged to use time wisely to finish tasks in the time required."),
		new FeedbackEntry("Needs Improvement", "# is encouraged to be more responsible in completing tasks without needing regular reminders."),
		new FeedbackEntry("Needs Improvement", "# needs to show by the quality of work and use of class time that $ is properly engaged in the learning process."),
		new FeedbackEntry("Needs Improvement", "# consistently needs reminders to use time effectively."),
		new FeedbackEntry("Math General Comments", "# is having considerable difficulty with math. I recommend $ work on studying # and #. This extra practice will help him/her feel more relaxed when doing math in the classroom."),
		new FeedbackEntry("Math General Comments", "# has a good understanding of all math concepts taught so far this year. $ continues to turn in excellent assignments and especially enjoys hands-on math activities."),
		new FeedbackEntry("Math General Comments", "# has a positive attitude towards math but continues to have trouble in a few key areas. $ should practice every evening at home. Areas that need extra attention are # and #."),
		new FeedbackEntry("Math General Comments", "# demonstrates a good understanding of all math concepts studied and communicates with clarity and good justification of reasoning."),
		new FeedbackEntry("Math General Comments", "# needs to work on increasing $ speed in math facts. Should continue with daily practice with a focus on addition, subtraction, multiplication and division."),
		new FeedbackEntry("Math General Comments", "# seems to need continuous encouragement in math. $ continues to struggle with basic math concepts for $ grade level."),
		new FeedbackEntry("Math General Comments", "# is having a difficult time in certain areas of math. Areas in need of extra work are #. Working on these problem areas every night would help improve $ learning outcomes."),
		new FeedbackEntry("Math General Comments", "# is struggling to keep up in math. $ could benefit from practicing the multiplication table and should also continue to practice the long division process."),
		new FeedbackEntry("Math General Comments", "# is easily distracted during math lessons and behavioral issues are interfering with $ learning. We will be working on more difficult subjects and $ will struggle if $ does not pay attention in class."),
		new FeedbackEntry("Math General Comments", "# is having trouble with math tests. $ does well on assignments, but does not seem to retain information for tests. I always give a week’s notice before tests, so please be sure # studies and adequately prepares for them as they approach."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "#’s (comprehension, spelling, reading) has greatly improved, but $ still needs extra work in (comprehension, spelling, reading). Please contact me if you need supplemental learning materials to use at home for practice."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# is conscious of putting care into $ daily writing work, responses to challenges posed and frequently goes beyond the minimum requirements for assignments or what is asked to be done."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# has trouble with his handwriting. I believe $ can form letters well, but has to slow down and take a little more time. Neater handwriting will improve $ schoolwork overall."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# makes a good effort to make $ handwriting legible; models; design briefs; experiments; narratives. $ is able to print on the lines, use good spacing, font sizes, word formats and form letters correctly."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# needs to focus on her spelling. More improvement is needed in the areas of (dictation, weekly spelling tests, sentence structure). Daily practice at home will help improve $ results."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# shows the ability to quickly use spelling, punctuation, subject terms and grammar rules that were taught earlier or recently taught. $ is able to quickly learn new skills and is eager to apply them in real life or to $ writing in the subject."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# is having considerable difficulty with reading, exploring, analyzing, synthesizing content or concepts."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# has good command of language for the subject particularly with fluency and comprehension to convince others."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# speaks well in front of the class/familiar audience/non familiar audience, but requires improvement in written language. $ is having trouble with (dictation, copying words correctly, story writing, creating logical sequences, writing an investigation, designing steps). Further practice is needed in this area."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# continues to make excellent progress in spelling and reading. Works hard to submit work that is free of grammatical errors."),
		new FeedbackEntry("Language and Subject Content Understanding (General)", "# has difficulty remembering previously discussed topics/contents/writings skills often makes errors with punctuation, grammar, and overall sentence structure. Basic writing skills need improvement."),
		new FeedbackEntry("Reading Responses", "# is able to offer direct responses to $ readings of content and supports ideas with sound reasoning and specific examples."),
		new FeedbackEntry("Reading Responses", "# is learning to offer more direct responses to her reading experiences supported by reasons, examples, and details."),
		new FeedbackEntry("Reading Responses", "# needs frequent support to offer direct responses to $ reading of content experiences supported by reasons, examples, and details."),
		new FeedbackEntry("Reading Comprehension or Text", "# shows good ability when completing reading comprehension tests or text about a topic."),
		new FeedbackEntry("Reading Comprehension or Text", "# would benefit from extra practice with reading aloud and discussion of content."),
		new FeedbackEntry("Reading Comprehension or Text", "# consistently demonstrates comprehension of short-spoken texts by answering questions, and explaining the events or ideas and concepts described."),
		new FeedbackEntry("Reading Comprehension or Text", "# consistently reads grade-level material or content independently."),
		new FeedbackEntry("Reading Comprehension or Text", "# uses good editing skills and correctly places capitals, quotation marks, question marks, apostrophes, commas, and periods."),
		new FeedbackEntry("Reading Comprehension or Text", "# is doing a good job of breaking a story or text into paragraphs."),
		new FeedbackEntry("Reading Comprehension or Text", "# determines various forms of writing and identifies important ideas and concepts through the development of insightful questions and answers."),
		new FeedbackEntry("Reading Comprehension or Text", "# is able to analyze character actions, story plots, and shows strong fluency with reading."),
		new FeedbackEntry("Response Journal", "# uses correct spelling, grammar and punctuation when writing simple sentences."),
		new FeedbackEntry("Response Journal", "# is encouraged to show increased attention to the use of correct spelling, grammar and punctuation with general writing skills."),
		new FeedbackEntry("Response Journal", "# needs more time and practice in the use of correct spelling, grammar and punctuation with general writing skills."),
		new FeedbackEntry("Response Journal", "# requires considerable assistance to achieve the correct spelling, grammar and punctuation when writing simple sentences."),
		new FeedbackEntry("Note Taking", "# shows an excellent understanding of note-taking from lectures and readings in preparation for tests and assignments."),
		new FeedbackEntry("Note Taking", "# requires ongoing support to develop an understanding of note-taking from lectures and readings in preparation for tests.")
	};
}
